# Generated by Django 5.0.6 on 2026-04-24 10:48

import apps.members.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=apps.members.models.generate_card_number, help_text='Physical card number e.g. MEM-AB12CD34', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.CharField(choices=[('STANDARD', 'Standard'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='STANDARD', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Max negative balance allowed. 0 = prepay only.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('home_branch', models.ForeignKey(blank=True, help_text='Primary branch. NULL = valid at all branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive=credit, Negative=debit', max_digits=10)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit (Top-up)'), ('DEBIT', 'Debit (Purchase)'), ('REVERSAL', 'Reversal (Correction)'), ('REFUND', 'Refund')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='billing.sale')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='idx_member_phone'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['card_number'], name='idx_member_card'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['member', 'created_at'], name='idx_ledger_member_date'),
        ),
    ]
