# Generated by Django 6.0.4 on 2026-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='itemno',
            field=models.IntegerField(default=0),
        ),
    ]
