# Generated by Django 5.0.6 on 2026-04-25 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('EARLY_OUT', 'Early Out')], default='PRESENT', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(default=0.0, help_text='1.0=exact, 0.6=threshold')),
                ('photo_path', models.CharField(blank=True, help_text='Path to the captured photo', max_length=255)),
                ('device_info', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='accounts.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='idx_attendance_user_time'), models.Index(fields=['branch', 'timestamp'], name='idx_attendance_branch_time')],
            },
        ),
    ]
