# Generated by Django 5.0.6 on 2026-04-23 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(db_index=True, help_text="Short billing code e.g. 'CB1', 'TEA', 'PR2'", max_length=10, unique=True)),
                ('item_type', models.CharField(choices=[('FOOD', 'Food'), ('BEVERAGE', 'Beverage'), ('COMBO', 'Combo Meal'), ('ADD_ON', 'Add-on / Extra')], default='FOOD', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Default price. Override per branch via BranchMenuItem.', max_digits=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='GST percentage e.g. 5.00 or 18.00', max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.PositiveIntegerField(default=5, help_text='Estimated prep time in minutes')),
                ('tags', models.JSONField(blank=True, default=list, help_text='e.g. ["veg", "spicy", "bestseller"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
            ],
            options={
                'ordering': ['category', 'short_code'],
            },
        ),
        migrations.CreateModel(
            name='BranchMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_overrides', to='accounts.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='inventory.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Use negative for reductions e.g. -3')),
                ('action', models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Sold (Auto)'), ('WASTE', 'Wasted / Spoiled'), ('ADJUST', 'Manual Adjustment'), ('TRANSFER', 'Branch Transfer')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='accounts.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='inventory.menuitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='idx_item_cat_available'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='idx_item_name'),
        ),
        migrations.AlterUniqueTogether(
            name='branchmenuitem',
            unique_together={('branch', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['menu_item', 'branch'], name='idx_stock_item_branch'),
        ),
    ]
