# Generated by Django 5.0.6 on 2026-05-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_ACTIVATED', 'User activated'), ('PASSWORD_RESET', 'Password reset'), ('FACE_REGISTERED', 'Face registered'), ('BRANCH_CREATED', 'Branch created'), ('BRANCH_UPDATED', 'Branch updated'), ('BRANCH_TOGGLED', 'Branch activated/deactivated'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='accounts.branch')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['performed_by', 'created_at'], name='idx_audit_user_date'), models.Index(fields=['action_type'], name='idx_audit_action')],
            },
        ),
    ]
